//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promote.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type string is empty.
        /// </summary>
        internal static string EmptyType {
            get {
                return ResourceManager.GetString("EmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option type &apos;{0}&apos; for enum mapping..
        /// </summary>
        internal static string InvalidOptionType {
            get {
                return ResourceManager.GetString("InvalidOptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed type string: property without value..
        /// </summary>
        internal static string MalformedType {
            get {
                return ResourceManager.GetString("MalformedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCI command &apos;{0}&apos; canceled..
        /// </summary>
        internal static string UCICommandCancel {
            get {
                return ResourceManager.GetString("UCICommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCI command &apos;{0}&apos; failed..
        /// </summary>
        internal static string UCICommandFail {
            get {
                return ResourceManager.GetString("UCICommandFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCI command &apos;{0}&apos; timed out..
        /// </summary>
        internal static string UCICommandTimeout {
            get {
                return ResourceManager.GetString("UCICommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property &apos;{0}&apos; in type string..
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported option type &apos;{0}&apos;..
        /// </summary>
        internal static string UnsupportedOptionType {
            get {
                return ResourceManager.GetString("UnsupportedOptionType", resourceCulture);
            }
        }
    }
}
